### ISSUE TITLE
Is it possible to debug an extension while debugging the host?

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode-wiki#29]
Hello

I'm not sure this question belongs here or in the main vscode repo.

If I launch vscode from source, then open an extension project, then try to debug that extension, I get the following error:

```
Configured debug type 'extensionHost' is not supported.: Error: Configured debug type 'extensionHost' is not supported.
    at Object.create (file:///D:/Downloads/vscode-fork/vscode/out/vs/base/common/errors.js:141:22)
    at file:///D:/Downloads/vscode-fork/vscode/out/vs/workbench/parts/debug/electron-browser/debugService.js:540:71
    at CompletePromise_ctor.CompletePromise_then [as then] (file:///D:/Downloads/vscode-fork/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
    at file:///D:/Downloads/vscode-fork/vscode/out/vs/workbench/parts/debug/electron-browser/debugService.js:532:80
    at _Base.Class.derive._creator.CompletePromise_then [as then] (file:///D:/Downloads/vscode-fork/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
    at DebugService.createProcess (file:///D:/Downloads/vscode-fork/vscode/out/vs/workbench/parts/debug/electron-browser/debugService.js:531:51)
    at file:///D:/Downloads/vscode-fork/vscode/out/vs/workbench/parts/debug/electron-browser/debugService.js:519:42
    at CompletePromise_ctor.CompletePromise_then [as then] (file:///D:/Downloads/vscode-fork/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
    at file:///D:/Downloads/vscode-fork/vscode/out/vs/workbench/parts/debug/electron-browser/debugService.js:500:93
    at Promise_ctor.CompletePromise_then [as then] (file:///D:/Downloads/vscode-fork/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
```

Is this expected?

**Comment by CoenraadS** [comment]
https://github.com/Microsoft/vscode/issues/9559
